#!/bin/bash
# eBay Multi-Channel Lister Pro - Launch Rollback Script
# Auto-generated by Atlas

set -euo pipefail

echo "========================================="
echo "🚨 STARTING EMERGENCY LAUNCH ROLLBACK 🚨"
echo "========================================="

# 1. Resolve target tag to roll back to
echo "Searching for the previous stable launch-ready git tag..."
PREV_TAG=$(git tag --sort=-creatordate | grep -E '^launch-ready' | sed -n '2p')

if [ -z "$PREV_TAG" ]; then
  echo "❌ ERROR: No previous stable launch-ready tag found in history."
  exit 1
fi

echo "Found target rollback tag: $PREV_TAG"

# 2. Checkout previous stable version
echo "Checking out version tag $PREV_TAG..."
git checkout "$PREV_TAG"

# 3. Trigger hosting redeployment/rollback
echo "Detecting deployment platform configurations..."
if [ -f vercel.json ]; then
  echo "Platform: Vercel. Running rollback command..."
  vercel rollback --yes
elif [ -f railway.toml ]; then
  echo "Platform: Railway. Triggering redeployment of current checked-out SHA..."
  # If railway CLI is present, run it. Otherwise alert.
  if command -v railway &> /dev/null; then
    railway redeploy --yes
  else
    echo "⚠️ Warning: railway CLI not found on path. Please deploy the current commit manually on the Railway console."
  fi
elif [ -f fly.toml ]; then
  echo "Platform: Fly.io. Running rollback command..."
  fly releases rollback
else
  echo "Platform: Generic Docker/Node. Redeploying using standard procedures..."
fi

# 4. Notify Alert Hook (Discord / Slack / Teams)
if [ -n "${DISCORD_WEBHOOK:-}" ]; then
  echo "Sending notifications to Discord webhook..."
  curl -s -H "Content-Type: application/json" \
       -X POST \
       -d "{\"content\":\"⚠️ **[EMERGENCY ROLLBACK]** eBay Multi-Channel Lister Pro has been rolled back to stable tag: \`$PREV_TAG\`\"}" \
       "$DISCORD_WEBHOOK" || echo "⚠️ Warning: Failed to send Discord webhook notice."
fi

echo "========================================="
echo "✅ EMERGENCY ROLLBACK SEQUENCE COMPLETE"
echo "========================================="
